server:
  port: 8080
logging:
  level:
    org.apache.jasper: TRACE
    org.apache.catalina.webresources: TRACE
    org.apache.catalina.core: DEBUG
    org.springframework.web.servlet.view: TRACE
    org.springframework.web.servlet.DispatcherServlet: TRACE
preferences:
  city: Hyderabad
  origin-country: India
  age: 35
  gender: Male	
  international-places: true 
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - mappings
          - beans 
